import telnetlib
import sys
import time
import re
import string
def connectdevice():
    HOST = '10.76.7.90'
    user = 'admin'
    password = "admin"
    tn = telnetlib.Telnet(HOST)
    tn.read_until(b'Enter login username:')
    tn.write(user.encode('ascii') + b'\n')
    tn.read_until(b'Enter login password:')
    tn.write(password.encode('ascii') + b'\n')
    time.sleep(3)
    tn.write(b'\n')
    tn.read_until(b'Main#')
    return tn
def configure_alteon():
    tn = connectdevice()
    tn.write(b'/c/slb/virt 1/service 80/pbind' + b'\n')
    tn.read_until(b'persistence mode:')
    tn.write(b'clientip'+ b'\n')
    tn.write(b'\n')
#    print('completed ')
    tn.read_until(b'Service#').decode('ascii')
    tn.write(b'cur' + b'\n')
    d=tn.read_until(b'Service#').decode('ascii')
#    print(d)
#    print('configuration done ')
    return tn
def revert_diff():
    t1 = configure_alteon()
    t1.write(b'diff'+ b'\n')
    fp=t1.read_until(b'Service#').decode('ascii')
    print(fp)
    t1.write(b'revert' + b'\n')
    t1.write(b'y' + b'\n')
    t1.read_until(b'Main#')
    print('revert done ')
def revertapply():
    tn = configure_alteon()
    tn.write(b'apply' + b'\n' )
    time.sleep(3)
    tn.write(b'y' + b'\n')
    time.sleep(7)
    tn.write(b'\n')
    tn.read_until(b'Service#')
    tn.write(b'diff flash' + b'\n')
    display=tn.read_until(b'Service#').decode('ascii')
    print(display)
    tn.write(b'revert apply' + b'\n')
    tn.write(b'y' + b'\n')
    time.sleep(3)
    tn.write(b'y' + b'\n')
    time.sleep(3)
    tn.read_until(b'Main#')
    print('revert apply done ')
def savereboot():
    tn = configure_alteon()
    tn.write(b'apply' + b'\n')
    time.sleep(3)
    tn.write(b'y' + b'\n')
    time.sleep(7)
    tn.write(b'\n' + b'\n')
    tn.read_until(b'Service#').decode('ascii')
    tn.write(b'save' + b'\n')
    time.sleep(2)
    tn.write(b'y' + b'\n')
    time.sleep(5)
    tn.write(b'\n')
    tn.read_until(b'#').decode('ascii')
    tn.write(b'/c/slb/virt 1/service 80/cur' + b'\n')
    display_1 = tn.read_until(b'#').decode('ascii')
    print(display_1)
    print('save complete')
    tn.write(b'/boot/reset' + b'\n')
    tn.write(b'y' + b'\n')
    tn.write(b'y'+ b'\n')
    time.sleep(120)
    t2 = connectdevice()
    t2.write(b'/c/slb/virt 1/service 80/cur' + b'\n')
    d1 = t2.read_until(b'#').decode('ascii')
    print(d1)
    print('save and reboot complete ')
revert_diff()
revertapply()
savereboot()